### PR TITLE
Vaulta Rebrand and New Contract Support

### LINKED ISSUE #35: Update Logos for Rebrand
## Current Art Work
- [Manager Icon](https://github.com/eosnetworkfoundation/ledger-app/blob/main/eos.png)
- [Device White gif](https://github.com/eosnetworkfoundation/ledger-app/blob/main/nanos_app_eos.gif)
- [Device Black gif](https://github.com/eosnetworkfoundation/ledger-app/blob/main/nanox_app_eos.gif)

[LedgerHQ notes and requirements](https://developers.ledger.com/docs/nano-app/design-requirements/)

### All Art Work
- The icon file does not contain any alpha channel
- Gradients are not allowed
- The background color should be solid

### Manager Art Work
- RVB colors only
- Pictogram color should be white
- Pictrogram stroke should be 4pt

### Device Art Work
- Pixel art icon
- Black on a white background for Nano S and white on a black background for Nano S Plus and X
- Safe area: 2px

### LINKED ISSUE #44: Update For New Contract Type
If updating to XYZ contract type , need to change this line.
https://github.com/eosnetworkfoundation/ledger-app/blob/3f6cc4ceb55226d80fed1c79c8754005ffc4fe07/src/eos_stream.c#L311

### LINKED ISSUE #48: Add swap contract support
Add ability to display swap action from EOS to new token.

### LINKED ISSUE #50: Validate Transaction Parameters to prevent crash
There is not enough checking on `transaction` action, and additional checks are needed to make sure the app does not crash. Specifically make sure `to` , `from`, `quantity` exists and can be dereferenced.

### PR DESCRIPTION
**Pull request by ericpassmore**
`EOS` is rebranding to `Vaulta`, with a new ticker symbol `A`.
- Update logos to match new branding
- Update to `Vaulta` branding name 
- Remove references to unsupported fairy wallet 
- Refactor tests to distinguish legacy `eosio` tests and `core.vaulta` tests 
- Add additional test cases for `A` token and `core.vaulta` contract 
- Add tests with bad transfer actions 

Update Golden Images for testing. Includes new subdirectory structure for Golden Images for better isolation of `eosio` and `vaulta` transactions. 

fixes #35 
fixes #44 
fixes #48 
fixes #50

### CODE REVIEW

File: src/eos_stream.c [hunk 1]
```diff
@@ -27,14 +27,20 @@
 #include "eos_parse_eosio.h"
 #include "eos_parse_unknown.h"
 
-#define EOSIO_TOKEN          0x5530EA033482A600
+#define EOSIO_TOKEN        0x5530EA033482A600
+#define CORE_VAULTA        0x452EA06CDA8E4C00
+
 #define EOSIO_TOKEN_TRANSFER 0xCDCD3C2D57000000
```
Comment (greg7mdp) [inline src/eos_stream.c]: I think we should rename this to `TRANSFER`  because it is not eosio specific.

File: src/eos_stream.c [hunk 2]
```diff
@@ -356,11 +367,17 @@ void printArgument(uint8_t argNum, txProcessingContext_t *context) {
 static bool isKnownAction(txProcessingContext_t *context) {
     name_t contractName = context->contractName;
     name_t actionName = context->contractActionName;
-    if (actionName == EOSIO_TOKEN_TRANSFER) {
+    
+    if (actionName == VAULTA_SWAPTO && contractName == CORE_VAULTA) {
```
Comment (greg7mdp) [inline src/eos_stream.c]: You could add `&& isTransferDataValid(context->currentFieldLength)` here as well.

File: tests/functional/apps/eos_transaction_builder.py [hunk 3]
```diff
@@ -131,8 +131,13 @@ def encode(self, data, encoder):
             encoder.update(encode_name(auth['actor']))
             encoder.update(encode_name(auth['permission']))
 
-        # pylint: disable=no-member
-        parameters = self.encode_action_parameters(data['data'])
+        parameters = bytes([0x00])
```
Comment (greg7mdp) [inline tests/functional/apps/eos_transaction_builder.py]: Is this line needed? Looks like we overwrite `parameters` just after.

File: tests/functional/apps/eos_transaction_builder.py [hunk 4]
```diff
@@ -149,7 +154,9 @@ def encode_action_parameters(self, data):
             parameters += pack(f'{len(memo)}s', data['memo'].encode())
 
         return parameters
-
+        
+class SwapToAction(TransferAction):
+    pass
```
Comment (greg7mdp) [inline tests/functional/apps/eos_transaction_builder.py:157]: needs to be implemented, right?

File: src/eos_stream.c (hunk 1 above)
Comment (ericpassmore) [reply src/eos_stream.c]: Screenshot 2025-05-14 at 2 13 22 PM

Agreed Renamed

File: tests/functional/apps/eos_transaction_builder.py (hunk 4 above)
Comment (ericpassmore) [reply tests/functional/apps/eos_transaction_builder.py:157]: I could use your advice here. Maybe drop the SwapToAction class?

`SwapToAction` has the same ABI and `TransferAction`. So I just copied the class definition into a new name. Line 185 is python code to have `SwapToAction` inherit from `TransferAction`. The pass is required by python otherwise a dummy method would be used.

File: tests/functional/apps/eos_transaction_builder.py (hunk 3 above)
Comment (ericpassmore) [reply tests/functional/apps/eos_transaction_builder.py]: hah, your right, I'm easily spooked by un-initiated variables.

File: tests/functional/apps/eos_transaction_builder.py [hunk 5]
```diff
@@ -131,8 +131,13 @@ def encode(self, data, encoder):
             encoder.update(encode_name(auth['actor']))
             encoder.update(encode_name(auth['permission']))
 
-        # pylint: disable=no-member
-        parameters = self.encode_action_parameters(data['data'])
+        parameters = bytes([0x00])
+        # if hex encoded data is already provided us that
```
Comment (ericpassmore) [inline tests/functional/apps/eos_transaction_builder.py]: fix spelling in comment

File: tests/functional/apps/eos_transaction_builder.py (hunk 4 above)
Comment (greg7mdp) [reply tests/functional/apps/eos_transaction_builder.py:157]: Oh I missed the inheritance, probably all good then!

**Comment by ericpassmore** [comment]
Tightened validation of transaction data, and added tests 
- valid empty 0x00 memo on transaction 
- invalid missing memo, no bytes, on transaction
